//go:build ignore

package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/zyedidia/armnalyzer/mra"
)

func xMask(bits string) string {
	mask := &bytes.Buffer{}
	mask.WriteString("0b")
	for _, c := range bits {
		switch c {
		case 'x':
			mask.WriteByte('0')
		default:
			mask.WriteByte('1')
		}
	}
	return mask.String()
}

func GenerateRegParseExpr(diagram string) string {
	parts := strings.Split(diagram, "|")
	b := 0
	buf := &bytes.Buffer{}
	first := true
	for i := len(parts) - 1; i >= 0; i-- {
		not := false
		_, bits, found := strings.Cut(parts[i], "=")
		if !found {
			_, bits, found = strings.Cut(parts[i], "!=")
			if found {
				not = true
			} else {
				bits = parts[i]
			}
		}

		if strings.Count(bits, "x") != len(bits) {
			mask := xMask(bits)

			var expr string
			if !not {
				expr = fmt.Sprintf("((insn >> %d) & %s) == 0b%s", b, mask, strings.ReplaceAll(bits, "x", "0"))
			} else {
				expr = fmt.Sprintf("((insn >> %d) & %s) != 0b%s", b, mask, bits)
			}
			if first {
				first = false
			} else {
				fmt.Fprint(buf, "&&")
			}
			fmt.Fprintf(buf, "(%s)", expr)
		}

		b += len(bits)
	}
	return buf.String()
}

func GenerateRegParseFunc(i int, diagram string) string {
	buf := &bytes.Buffer{}
	fmt.Fprintf(buf, "func parse_%d(insn uint32) bool {\n", i)
	fmt.Fprintf(buf, "\treturn %s\n", GenerateRegParseExpr(diagram))
	fmt.Fprintf(buf, "}\n")
	return buf.String()
}

func main() {
	flag.Parse()
	args := flag.Args()

	if len(args) <= 0 {
		log.Fatal("no input")
	}
	b, err := os.ReadFile(args[0])
	if err != nil {
		log.Fatal(err)
	}
	var records []mra.Record
	err = json.Unmarshal(b, &records)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("// Code generated by decode_gen arm64.json; DO NOT EDIT")
	fmt.Println("package main")
	fmt.Println()
	fmt.Println("var funcs = []func(uint32) bool{")
	for i := range records {
		fmt.Printf("\tparse_%d,\n", i)
	}
	fmt.Println("}")

	for i, r := range records {
		fmt.Println(GenerateRegParseFunc(i, r.RegDiagram))
	}
}
